export const ANIMATE_CLASSES_IN = [
  'animate__animated animate__bounceIn',
  'animate__animated animate__bounceInLeft',
  'animate__animated animate__bounceInUp',
  'animate__animated animate__fadeIn',
  'animate__animated animate__fadeInLeft',
  'animate__animated animate__fadeInUp',
  'animate__animated animate__flipInX',
  'animate__animated animate__rotateIn',
  'animate__animated animate__slideInLeft',
  'animate__animated animate__slideInUp',
  'animate__animated animate__rollIn',
]
export const ANIMATE_CLASSES_OUT = [
  'animate__animated animate__bounceOut',
  'animate__animated animate__bounceOutRight',
  'animate__animated animate__bounceOutDown',
  'animate__animated animate__fadeOut',
  'animate__animated animate__fadeOutRight',
  'animate__animated animate__fadeOutDown',
  'animate__animated animate__flipOutX',
  'animate__animated animate__rotateOut',
  'animate__animated animate__slideOutRight',
  'animate__animated animate__slideOutDown',
  'animate__animated animate__rollOut',
]
