export const MONACO_THEMES = {
  'solarized-light': {
    'base': 'vs',
    'inherit': true,
    'rules': [
      { 'foreground': '93a1a1', 'token': 'comment' },
      { 'foreground': '2aa198', 'token': 'string' },
      { 'foreground': 'd30102', 'token': 'string.regexp' },
      { 'foreground': 'd33682', 'token': 'constant.numeric' },
      { 'foreground': '268bd2', 'token': 'variable.language' },
      { 'foreground': '268bd2', 'token': 'variable.other' },
      { 'foreground': '859900', 'token': 'keyword' },
      { 'foreground': '073642', 'fontStyle': 'bold', 'token': 'storage' },
      { 'foreground': '268bd2', 'token': 'entity.name.class' },
      { 'foreground': '268bd2', 'token': 'entity.name.type.class' },
      { 'foreground': '268bd2', 'token': 'entity.name.function' },
      { 'foreground': '859900', 'token': 'punctuation.definition.variable' },
      { 'foreground': 'd30102', 'token': 'punctuation.section.embedded.begin' },
      { 'foreground': 'd30102', 'token': 'punctuation.section.embedded.end' },
      { 'foreground': 'b58900', 'token': 'constant.language' },
      { 'foreground': 'b58900', 'token': 'meta.preprocessor' },
      { 'foreground': 'd30102', 'token': 'support.function.construct' },
      { 'foreground': 'd30102', 'token': 'keyword.other.new' },
      { 'foreground': 'cb4b16', 'token': 'constant.character' },
      { 'foreground': 'cb4b16', 'token': 'constant.other' },
      { 'foreground': '268bd2', 'fontStyle': 'bold', 'token': 'entity.name.tag' },
      { 'foreground': '93a1a1', 'token': 'punctuation.definition.tag.begin' },
      { 'foreground': '93a1a1', 'token': 'punctuation.definition.tag.end' },
      { 'foreground': '93a1a1', 'token': 'entity.other.attribute-name' },
      { 'foreground': '268bd2', 'token': 'support.function' },
      { 'foreground': 'd30102', 'token': 'punctuation.separator.continuation' },
      { 'foreground': '859900', 'token': 'support.type' },
      { 'foreground': '859900', 'token': 'support.class' },
      { 'foreground': 'cb4b16', 'token': 'support.type.exception' }
    ],
    'colors': {
      'editor.foreground': '#586E75',
      'editor.background': '#FDF6E3',
      'editor.selectionBackground': '#073642',
      'editor.lineHighlightBackground': '#EEE8D5',
      'editorCursor.foreground': '#000000',
      'editorWhitespace.foreground': '#93A1A1'
    }
  },
  'solarized-dark': {
    'base': 'vs-dark',
    'inherit': true,
    'rules': [
      { 'foreground': '657b83', 'fontStyle': 'italic', 'token': 'comment' },
      { 'foreground': '2aa198', 'token': 'string' },
      { 'foreground': 'd30102', 'token': 'string.regexp' },
      { 'foreground': 'd33682', 'token': 'constant.numeric' },
      { 'foreground': '268bd2', 'token': 'variable.language' },
      { 'foreground': '268bd2', 'token': 'variable.other' },
      { 'foreground': '859900', 'token': 'keyword' },
      { 'foreground': '93a1a1', 'fontStyle': 'bold', 'token': 'storage' },
      { 'foreground': 'cb4b16', 'token': 'entity.name.class' },
      { 'foreground': 'cb4b16', 'token': 'entity.name.type.class' },
      { 'foreground': '268bd2', 'token': 'entity.name.function' },
      { 'foreground': '859900', 'token': 'punctuation.definition.variable' },
      { 'foreground': 'd30102', 'token': 'punctuation.section.embedded.begin' },
      { 'foreground': 'd30102', 'token': 'punctuation.section.embedded.end' },
      { 'foreground': 'b58900', 'token': 'constant.language' },
      { 'foreground': 'b58900', 'token': 'meta.preprocessor' },
      { 'foreground': 'cb4b16', 'token': 'support.function.construct' },
      { 'foreground': 'cb4b16', 'token': 'keyword.other.new' },
      { 'foreground': 'cb4b16', 'token': 'constant.character' },
      { 'foreground': 'cb4b16', 'token': 'constant.other' },
      { 'foreground': '6c71c4', 'token': 'entity.other.inherited-class' },
      { 'foreground': '268bd2', 'fontStyle': 'bold', 'token': 'entity.name.tag' },
      { 'foreground': '657b83', 'token': 'punctuation.definition.tag' },
      { 'foreground': '93a1a1', 'token': 'entity.other.attribute-name' },
      { 'foreground': '268bd2', 'token': 'support.function' },
      { 'foreground': 'd30102', 'token': 'punctuation.separator.continuation' },
      { 'foreground': '859900', 'token': 'support.type' },
      { 'foreground': '859900', 'token': 'support.class' },
      { 'foreground': 'cb4b16', 'token': 'support.type.exception' }
    ],
    'colors': {
      'editor.foreground': '#93A1A1',
      'editor.background': '#002B36',
      'editor.selectionBackground': '#073642',
      'editor.lineHighlightBackground': '#073642',
      'editorCursor.foreground': '#D30102',
      'editorWhitespace.foreground': '#93A1A1'
    }
  },
  'blue': {
    'base': 'vs-dark',
    'inherit': true,
    'rules': [
      { 'foreground': '7285b7', 'token': 'comment' },
      { 'foreground': 'ffffff', 'token': 'keyword.operator.class' },
      { 'foreground': 'ffffff', 'token': 'keyword.operator' },
      { 'foreground': 'ffffff', 'token': 'constant.other' },
      { 'foreground': 'ffffff', 'token': 'source.php.embedded.line' },
      { 'foreground': 'ff9da4', 'token': 'variable' },
      { 'foreground': 'ff9da4', 'token': 'support.other.variable' },
      { 'foreground': 'ff9da4', 'token': 'string.other.link' },
      { 'foreground': 'ff9da4', 'token': 'string.regexp' },
      { 'foreground': 'ff9da4', 'token': 'entity.name.tag' },
      { 'foreground': 'ff9da4', 'token': 'entity.other.attribute-name' },
      { 'foreground': 'ff9da4', 'token': 'meta.tag' },
      { 'foreground': 'ff9da4', 'token': 'declaration.tag' },
      { 'foreground': 'ffc58f', 'token': 'constant.numeric' },
      { 'foreground': 'ffc58f', 'token': 'constant.language' },
      { 'foreground': 'ffc58f', 'token': 'support.constant' },
      { 'foreground': 'ffc58f', 'token': 'constant.character' },
      { 'foreground': 'ffc58f', 'token': 'variable.parameter' },
      { 'foreground': 'ffc58f', 'token': 'punctuation.section.embedded' },
      { 'foreground': 'ffc58f', 'token': 'keyword.other.unit' },
      { 'foreground': 'ffeead', 'token': 'entity.name.class' },
      { 'foreground': 'ffeead', 'token': 'entity.name.type.class' },
      { 'foreground': 'ffeead', 'token': 'support.type' },
      { 'foreground': 'ffeead', 'token': 'support.class' },
      { 'foreground': 'd1f1a9', 'token': 'string' },
      { 'foreground': 'd1f1a9', 'token': 'constant.other.symbol' },
      { 'foreground': 'd1f1a9', 'token': 'entity.other.inherited-class' },
      { 'foreground': 'd1f1a9', 'token': 'markup.heading' },
      { 'foreground': '99ffff', 'token': 'keyword.operator' },
      { 'foreground': '99ffff', 'token': 'constant.other.color' },
      { 'foreground': 'bbdaff', 'token': 'entity.name.function' },
      { 'foreground': 'bbdaff', 'token': 'meta.function-call' },
      { 'foreground': 'bbdaff', 'token': 'support.function' },
      { 'foreground': 'bbdaff', 'token': 'keyword.other.special-method' },
      { 'foreground': 'bbdaff', 'token': 'meta.block-level' },
      { 'foreground': 'ebbbff', 'token': 'keyword' },
      { 'foreground': 'ebbbff', 'token': 'storage' },
      { 'foreground': 'ebbbff', 'token': 'storage.type' },
      { 'foreground': 'ebbbff', 'token': 'entity.name.tag.css' },
      { 'foreground': 'ffffff', 'background': 'f99da5', 'token': 'invalid' },
      { 'foreground': 'ffffff', 'background': 'bbdafe', 'token': 'meta.separator' },
      { 'foreground': 'ffffff', 'background': 'ebbbff', 'token': 'invalid.deprecated' }
    ],
    'colors': {
      'editor.foreground': '#FFFFFF',
      'editor.background': '#002451',
      'editor.selectionBackground': '#003F8E',
      'editor.lineHighlightBackground': '#00346E',
      'editorCursor.foreground': '#FFFFFF',
      'editorWhitespace.foreground': '#404F7D'
    }
  },
  'abyss': {
    'base': 'vs-dark',
    'inherit': true,
    'rules': [
      { 'foreground': '473c45', 'token': 'comment' },
      { 'foreground': '805978', 'token': 'string' },
      { 'foreground': 'a8885a', 'token': 'constant' },
      { 'foreground': '596380', 'token': 'variable.parameter' },
      { 'foreground': '596380', 'token': 'variable.other' },
      { 'foreground': '728059', 'token': 'keyword - keyword.operator' },
      { 'foreground': '728059', 'token': 'keyword.operator.logical' },
      { 'foreground': '9ebf60', 'token': 'storage' },
      { 'foreground': '6078bf', 'token': 'entity' },
      { 'fontStyle': 'italic', 'token': 'entity.other.inherited-class' },
      { 'foreground': '8a4b66', 'token': 'support' },
      { 'foreground': '893062', 'token': 'support.type.exception' },
      { 'background': '5f0047', 'token': 'invalid' },
      { 'background': '371d28', 'token': 'meta.function.section' }
    ],
    'colors': {
      'editor.foreground': '#DDE6CF',
      'editor.background': '#0D0D0D',
      'editor.selectionBackground': '#40002F',
      'editor.lineHighlightBackground': '#000000',
      'editorCursor.foreground': '#7F005D',
      'editorWhitespace.foreground': '#BFBFBF'
    }
  }
};
